# Generated by Django 2.0.4 on 2018-04-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a player name', max_length=20)),
                ('wins', models.SmallIntegerField()),
                ('losses', models.SmallIntegerField()),
                ('match', models.SmallIntegerField()),
                ('bye', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tournament name', max_length=20)),
                ('reference_code', models.CharField(max_length=10, null=True)),
                ('current_round', models.SmallIntegerField(default=1)),
                ('password', models.CharField(blank=True, help_text='Enter a tournament password', max_length=50)),
                ('status', models.CharField(blank=True, choices=[('w', 'Waiting for players'), ('a', 'Active'), ('c', 'Completed')], default='w', help_text='Tournament status', max_length=1)),
                ('players', models.ManyToManyField(related_name='tounaments', to='bracketgen.Player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='bracketgen.Player')),
            ],
        ),
    ]
